CREATE TABLE ORIGINAL_RECEIPT (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL);

CREATE TABLE RECEIPT (
    id INTEGER PRIMARY KEY,
    taxNumber VARCHAR (0),
    transactionDate DATE, receiptNumber VARCHAR,
    cashId VARCHAR,
    total VARCHAR,
    status INTEGER (2) DEFAULT (0),
    sourceId INTEGER REFERENCES ORIGINAL_RECEIPT (id) ON DELETE CASCADE);

